#!/usr/bin/env python3

def guess_number(n):
    while True: 
        user = int(input("Enter number: "))
        if user > n:
            print('Too High')
        elif user < n:
            print('Too Low')
        else
            print('you win')
            return -->> will exit immedialtey from the function
        break
guess_number(23)
