#!/usr/bin/env python3

def guess_number(n):
    condition = True
    while True:
        if n == 23:
            print('WIN')
        elif n > 23:
            print('your guess is too high')
        elif n < 23:
            print('your guess it too low')
            return -->> will exit immedialtey from the function
        break
guess_number(23)
